# Generated by Django 3.2.7 on 2021-10-20 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20211020_2259'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ZooMerchant',
            new_name='ZooMerch',
        ),
    ]
